### ISSUE TITLE
Place for Questions / Comments ? Slack / Gitter ?

### ISSUE THREAD

**Issue by ghedwards** [cingulo/flutter-sample#10]
I think this project is great, it would be nice to be able to chat about specifics in the implementations in this project.

For example: 
I've found when my API returns a 401 for an unauthenticated error I get an unhandled exception.. [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'UnauthenticatedError', is this something that should be better catered for or something perhaps I need to implement myself ?

**Comment by rserro** [comment]
Hi @ghedwards ! I'm on a hurry today and tomorrow (lots of stuff to do), so I'll answer this by wednesday. Thanks for the understanding!

**Comment by rserro** [comment]
Hi! This project is still to small to have a separete discussion tool other than here. Please, post your of ui_dart_state.cc(148) so that we may have a clue on how to help you with the UnauthenticatedError.
