### ISSUE TITLE
minSdkVersion needs to be set to 18, doesn't build

### ISSUE THREAD

**Issue by sgehrman** [cingulo/flutter-sample#16]
I'm on Linux, building the code to run on the Android simulator.

I had to set         minSdkVersion 18
in andriod/appp/build.gradle to get it to run.

You should update this in the repo.

Launching lib/main.dart on Android SDK built for x86 in debug mode...
/home/steve/google/flutter-sample/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:flutter_secure_storage] /home/steve/google/flutter-sample/build/flutter_secure_storage/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 18,
		or use tools:overrideLibrary="com.it_nomads.fluttersecurestorage" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:flutter_secure_storage] /home/steve/google/flutter-sample/build/flutter_secure_storage/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 18,
  		or use tools:overrideLibrary="com.it_nomads.fluttersecurestorage" to force usage (may lead to runtime failures)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by rserro** [comment]
Thanks @sgehrman
