### ISSUE TITLE
Target of URI doesn't exist: 'app_di.inject.dart'

### ISSUE THREAD

**Issue by mshwf** [cingulo/flutter-sample#18]
This happens in the `import` line in the [`app_di.dart` file](https://github.com/cingulo/flutter-sample/blob/develop/lib/app/app_di.dart#L8)

![image](https://user-images.githubusercontent.com/10940379/70390936-56e99380-19d8-11ea-86d7-2ed4ba05eb0d.png)

**Comment by rserro** [comment]
Hi @mshwf !
Try the following:
```
$ cd <repository-root>
$ git clone https://github.com/cingulo/inject.dart.git vendor/inject.dart
$ flutter packages pub run build_runner build --build-filter "lib/data/*/*.dart" --delete-conflicting-outputs
$ flutter packages pub run build_runner build --build-filter "lib/app/*.dart" --delete-conflicting-outputs
```
If that does not work, re-run the last two commands without --delete-conflicting-outputs:
```
$ flutter packages pub run build_runner build --build-filter "lib/data/*/*.dart"
$ flutter packages pub run build_runner build --build-filter "lib/app/*.dart"
```
Do not mind if the first of this commands issues error. Run both in sequence and it will be fine.

**Comment by mshwf** [comment]
Thanks @rserro
