### ISSUE TITLE
Any idea how to resolve these errors ?

### ISSUE THREAD

**Issue by ghedwards** [cingulo/flutter-sample#8]
![image](https://user-images.githubusercontent.com/125586/67995854-6ae2fc80-fc98-11e9-8898-19fb05b90e5b.png)
It looks like the generated injector code is resolving the classes differently. ie ../ instead of package:com_cingulo_sample ?

**Comment by ghedwards** [comment]
Looks like this is only an issue if using VSCode, Android Studio appears to work correctly.

**Comment by rserro** [comment]
Hi @ghedwards! I use VSCode with no problems. Try this: if you look at `<flutter-sample>/.vscode` you will see a `settings.json` file having `**/*.inject.*` inside `files.exclude`. Use this settings file in your VSCode Workspace and I think it will solve the problem.

**Comment by rserro** [comment]
At last, this is the script I use when there is any sort of dependency injection generated files problems:
```
cd <flutter-sample>/lib
find . -name "*.inject.*" -type f -delete
cd ..
flutter packages pub run build_runner build --delete-conflicting-outputs
flutter clean
# should be good now
```
